apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-app-api
  namespace: bushkovskiy
spec:
  selector:
    matchLabels:
      app: time-app-api
  template:
    metadata:
      labels:
        app: time-app-api
    spec:
      containers:
        - name: time-app-api
          image: garikvelikiy/time-app-api-dev:1.1.7
          env:
            - name: MYSQL_DB
              value: mysql
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: time-app-api
  namespace: bushkovskiy
spec:
  type: LoadBalancer
  selector:
    app: time-app-api
  ports:
    - port: 5555
      targetPort: 5000
